### ISSUE TITLE
Allow Case-sensitive Matchwords

### ISSUE THREAD

**Issue by jfilter** [thisisparker/track-the-news#3]
For the the German FOIA, the abbr. is 'IFG'. Testing for it has to be done case-sensitive otherwise I would get too many false positives. My suggestions: add a new file e.g. 'matchwords-case-sensitive'.

**Comment by thisisparker** [comment]
Oh that's a good idea, I'll do that.

**Comment by thisisparker** [comment]
Should be fixed with 057f8bba2ee8af1d44362c76abc961664cc31a21, which I've pushed to pip as `0.1.8.14`. Try updating from there and then running `trackthenews --config` one more time?
